---
:HtmlBlockTag:
  :paragraph: p
  :ordered_list: ol
  :unordered_list: ul
  :list_item: li
  :definition_list: dl
  :definition_term: dt
  :definition_descr: dd
  :table: table
  :table_row: tr
  :quote: blockquote
  :example: pre
  :src: pre
  :inline_example: pre
  :center: div
  :heading1: h1
  :heading2: h2
  :heading3: h3
  :heading4: h4
  :heading5: h5
  :heading6: h6
  :title: h1
